project:
  type: website

website:
  title: "陈美林 - 水土保持与荒漠化防治"
  navbar:
    left:
      - href: index.qmd
        text: 首页
      - href: about.qmd
        text: 关于我
      - href: research.qmd
        text: 科研经历
    right:
      - icon: github
        href: https://github.com/meilin090
      - icon: envelope
        href: mailto:2806048253@qq.com
  
  page-footer:
    center: "© 2026 陈美林 - 西南大学 | 华中农业大学"

format:
  html:
    theme:
      - cosmo
    css: styles.css
    toc: true